"""baseline: esquema inicial completo del ERP

Revision ID: 99c028642b89
Revises: 
Create Date: 2026-07-02 12:00:29.696849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99c028642b89'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('centros_costo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.Enum('MARCA', 'AREA', 'PROYECTO', name='tipocentrocosto'), nullable=False),
    sa.Column('marca_asociada', sa.String(length=100), nullable=True),
    sa.Column('responsable', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('centros_costo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_centros_costo_codigo'), ['codigo'], unique=True)

    op.create_table('clientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nit_cc', sa.String(length=20), nullable=False),
    sa.Column('dv', sa.String(length=1), nullable=True),
    sa.Column('razon_social', sa.String(length=200), nullable=False),
    sa.Column('nombre_comercial', sa.String(length=200), nullable=True),
    sa.Column('tipo_persona', sa.String(length=20), nullable=False),
    sa.Column('regimen_iva', sa.String(length=50), nullable=False),
    sa.Column('direccion', sa.String(length=300), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('departamento', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('celular', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('contacto_nombre', sa.String(length=200), nullable=True),
    sa.Column('contacto_cargo', sa.String(length=100), nullable=True),
    sa.Column('lista_precios', sa.String(length=50), nullable=False),
    sa.Column('cupo_credito', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('dias_credito', sa.Integer(), nullable=False),
    sa.Column('retiene_fuente', sa.Boolean(), nullable=False),
    sa.Column('retiene_iva', sa.Boolean(), nullable=False),
    sa.Column('retiene_ica', sa.Boolean(), nullable=False),
    sa.Column('tarifa_reteica', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('alegra_id', sa.Integer(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clientes_alegra_id'), ['alegra_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clientes_nit_cc'), ['nit_cc'], unique=True)

    op.create_table('cuentas_por_cobrar',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero_factura', sa.String(length=50), nullable=False),
    sa.Column('fecha_emision', sa.Date(), nullable=False),
    sa.Column('cliente_nit', sa.String(length=20), nullable=False),
    sa.Column('nombre_cliente', sa.String(length=200), nullable=True),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('valor_factura', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('abonos', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('saldo_pendiente', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'PARCIAL', 'PAGADO', 'VENCIDO', 'ANULADO', name='estadodocumento'), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_factura')
    )
    op.create_table('cuentas_por_pagar',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero_documento', sa.String(length=50), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('proveedor_nit', sa.String(length=20), nullable=False),
    sa.Column('razon_social', sa.String(length=200), nullable=True),
    sa.Column('concepto', sa.String(length=300), nullable=True),
    sa.Column('valor', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('abonos', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('saldo_pendiente', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'PARCIAL', 'PAGADO', 'VENCIDO', 'ANULADO', name='estadodocumento'), nullable=False),
    sa.Column('compra_id', sa.Integer(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_documento')
    )
    op.create_table('parametros_nomina',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('concepto', sa.String(length=200), nullable=False),
    sa.Column('valor_porcentaje', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('concepto')
    )
    op.create_table('parametros_tributarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('concepto', sa.String(length=200), nullable=False),
    sa.Column('tarifa_valor', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.Column('base_aplica', sa.String(length=200), nullable=True),
    sa.Column('cuenta_puc', sa.String(length=20), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('concepto')
    )
    op.create_table('periodos_contables',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.String(length=7), nullable=False),
    sa.Column('estado', sa.Enum('ABIERTO', 'CERRADO', name='estadoperiodo'), nullable=False),
    sa.Column('fecha_cierre', sa.Date(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anio', 'mes', name='uq_periodo_anio_mes'),
    sa.UniqueConstraint('periodo')
    )
    op.create_table('plan_cuentas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo_puc', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('clase', sa.Enum('ACTIVO', 'PASIVO', 'PATRIMONIO', 'INGRESO', 'GASTO', 'COSTO', name='clasecuenta'), nullable=False),
    sa.Column('naturaleza', sa.Enum('DEBITO', 'CREDITO', name='naturalezacuenta'), nullable=False),
    sa.Column('nivel', sa.Enum('CLASE', 'GRUPO', 'CUENTA', 'SUBCUENTA', 'AUXILIAR', name='nivelcuenta'), nullable=False),
    sa.Column('cuenta_padre_id', sa.Integer(), nullable=True),
    sa.Column('requiere_tercero', sa.Boolean(), nullable=False),
    sa.Column('requiere_centro_costo', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cuenta_padre_id'], ['plan_cuentas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plan_cuentas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_cuentas_codigo_puc'), ['codigo_puc'], unique=True)

    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nit_cc', sa.String(length=20), nullable=False),
    sa.Column('dv', sa.String(length=1), nullable=True),
    sa.Column('razon_social', sa.String(length=200), nullable=False),
    sa.Column('nombre_comercial', sa.String(length=200), nullable=True),
    sa.Column('tipo_persona', sa.String(length=20), nullable=False),
    sa.Column('regimen_iva', sa.String(length=50), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('direccion', sa.String(length=300), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('departamento', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('celular', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('contacto_nombre', sa.String(length=100), nullable=True),
    sa.Column('contacto_cargo', sa.String(length=100), nullable=True),
    sa.Column('dias_credito', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proveedores_nit_cc'), ['nit_cc'], unique=True)

    op.create_table('terceros',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nit_cc', sa.String(length=20), nullable=False),
    sa.Column('dv', sa.String(length=1), nullable=True),
    sa.Column('razon_social', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.Enum('CLIENTE', 'PROVEEDOR', 'EMPLEADO', 'MIXTO', name='tipotercero'), nullable=False),
    sa.Column('tipo_persona', sa.Enum('NATURAL', 'JURIDICA', name='tipopersona'), nullable=True),
    sa.Column('regimen_iva', sa.Enum('RESPONSABLE', 'NO_RESPONSABLE', 'GRAN_CONTRIBUYENTE', name='regimeniva'), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('terceros', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_terceros_nit_cc'), ['nit_cc'], unique=True)

    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nombre_completo', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("rol IN ('Admin', 'Administradora', 'Auxiliar')", name='ck_usuarios_rol'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_id'), ['id'], unique=False)

    op.create_table('asientos_contables',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('tipo_documento', sa.String(length=50), nullable=True),
    sa.Column('modulo_origen', sa.String(length=50), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('periodo_id', sa.Integer(), nullable=True),
    sa.Column('anulado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodos_contables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compras_documentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('proveedor_razon_social', sa.String(length=200), nullable=True),
    sa.Column('proveedor_nit', sa.String(length=20), nullable=True),
    sa.Column('ref_proveedor', sa.String(length=100), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('descuento_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('base_gravable', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('iva_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('retefuente', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('reteiva', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('reteica', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('estado_pago', sa.String(length=20), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compras_documentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compras_documentos_numero'), ['numero'], unique=True)

    op.create_table('pagos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero_comprobante', sa.String(length=20), nullable=False),
    sa.Column('tipo', sa.Enum('CXC', 'CXP', name='tipopago'), nullable=False),
    sa.Column('cxc_id', sa.Integer(), nullable=True),
    sa.Column('cxp_id', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('saldo_anterior', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('saldo_nuevo', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pagos_cxc_id'), ['cxc_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pagos_cxp_id'), ['cxp_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pagos_numero_comprobante'), ['numero_comprobante'], unique=True)

    op.create_table('productos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('categoria', sa.Enum('BIOCIDA', 'FERTILIZANTE', 'COADYUVANTE', 'DESINFECTANTE', 'OTRO', name='categoriaproducto'), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=False),
    sa.Column('centro_costo_id', sa.Integer(), nullable=True),
    sa.Column('unidad_medida', sa.Enum('LITRO', 'GALON', 'KILO', 'UNIDAD', 'CAJA', 'CANECA', name='unidadmedida'), nullable=False),
    sa.Column('contenido_neto', sa.String(length=50), nullable=True),
    sa.Column('precio_venta', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('precio_costo', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('tarifa_iva', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('stock_actual', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('stock_minimo', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('alegra_id', sa.Integer(), nullable=True),
    sa.Column('registro_ica', sa.String(length=50), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['centro_costo_id'], ['centros_costo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_productos_alegra_id'), ['alegra_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_productos_sku'), ['sku'], unique=True)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('saldos_iniciales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=False),
    sa.Column('centro_costo_id', sa.Integer(), nullable=True),
    sa.Column('tercero_id', sa.Integer(), nullable=True),
    sa.Column('debito', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('credito', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['centro_costo_id'], ['centros_costo.id'], ),
    sa.ForeignKeyConstraint(['cuenta_id'], ['plan_cuentas.id'], ),
    sa.ForeignKeyConstraint(['tercero_id'], ['terceros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ventas_documentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('centro_costo_id', sa.Integer(), nullable=True),
    sa.Column('vendedor', sa.String(length=200), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('descuento_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('base_gravable', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('iva_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('retefuente', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('reteiva', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('reteica', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('estado', sa.Enum('BORRADOR', 'CONFIRMADA', 'FACTURADA', 'ANULADA', name='estadoventa'), nullable=False),
    sa.Column('estado_pago', sa.Enum('PENDIENTE', 'PARCIAL', 'PAGADO', name='estadopago'), nullable=False),
    sa.Column('alegra_id', sa.Integer(), nullable=True),
    sa.Column('alegra_numero', sa.String(length=50), nullable=True),
    sa.Column('cufe', sa.String(length=200), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['centro_costo_id'], ['centros_costo.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ventas_documentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ventas_documentos_alegra_id'), ['alegra_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ventas_documentos_numero'), ['numero'], unique=True)

    op.create_table('compras_detalles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('compra_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=300), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('descuento_porcentaje', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('iva_porcentaje', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('subtotal_linea', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('iva_valor', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_linea', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['compra_id'], ['compras_documentos.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimientos_asiento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asiento_id', sa.Integer(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=False),
    sa.Column('tercero_id', sa.Integer(), nullable=True),
    sa.Column('centro_costo_id', sa.Integer(), nullable=True),
    sa.Column('debito', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('credito', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asiento_id'], ['asientos_contables.id'], ),
    sa.ForeignKeyConstraint(['centro_costo_id'], ['centros_costo.id'], ),
    sa.ForeignKeyConstraint(['cuenta_id'], ['plan_cuentas.id'], ),
    sa.ForeignKeyConstraint(['tercero_id'], ['terceros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimientos_inventario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('ENTRADA', 'SALIDA', 'AJUSTE_POSITIVO', 'AJUSTE_NEGATIVO', name='tipomovimientoinventario'), nullable=False),
    sa.Column('origen', sa.Enum('COMPRA', 'VENTA', 'AJUSTE_MANUAL', 'REVERSO_COMPRA', 'REVERSO_VENTA', name='origenmovimiento'), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('stock_antes', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('stock_despues', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('costo_unitario', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('compra_id', sa.Integer(), nullable=True),
    sa.Column('compra_detalle_id', sa.Integer(), nullable=True),
    sa.Column('venta_id', sa.Integer(), nullable=True),
    sa.Column('venta_detalle_id', sa.Integer(), nullable=True),
    sa.Column('motivo', sa.String(length=300), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movimientos_inventario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movimientos_inventario_compra_id'), ['compra_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimientos_inventario_producto_id'), ['producto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimientos_inventario_venta_id'), ['venta_id'], unique=False)

    op.create_table('ventas_detalles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('descuento_porcentaje', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('subtotal_linea', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('iva_porcentaje', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('iva_valor', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_linea', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('notas', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas_documentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ventas_detalles')
    with op.batch_alter_table('movimientos_inventario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimientos_inventario_venta_id'))
        batch_op.drop_index(batch_op.f('ix_movimientos_inventario_producto_id'))
        batch_op.drop_index(batch_op.f('ix_movimientos_inventario_compra_id'))

    op.drop_table('movimientos_inventario')
    op.drop_table('movimientos_asiento')
    op.drop_table('compras_detalles')
    with op.batch_alter_table('ventas_documentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ventas_documentos_numero'))
        batch_op.drop_index(batch_op.f('ix_ventas_documentos_alegra_id'))

    op.drop_table('ventas_documentos')
    op.drop_table('saldos_iniciales')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_id'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_productos_sku'))
        batch_op.drop_index(batch_op.f('ix_productos_alegra_id'))

    op.drop_table('productos')
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pagos_numero_comprobante'))
        batch_op.drop_index(batch_op.f('ix_pagos_cxp_id'))
        batch_op.drop_index(batch_op.f('ix_pagos_cxc_id'))

    op.drop_table('pagos')
    with op.batch_alter_table('compras_documentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compras_documentos_numero'))

    op.drop_table('compras_documentos')
    op.drop_table('asientos_contables')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_id'))
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    with op.batch_alter_table('terceros', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_terceros_nit_cc'))

    op.drop_table('terceros')
    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proveedores_nit_cc'))

    op.drop_table('proveedores')
    with op.batch_alter_table('plan_cuentas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_cuentas_codigo_puc'))

    op.drop_table('plan_cuentas')
    op.drop_table('periodos_contables')
    op.drop_table('parametros_tributarios')
    op.drop_table('parametros_nomina')
    op.drop_table('cuentas_por_pagar')
    op.drop_table('cuentas_por_cobrar')
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clientes_nit_cc'))
        batch_op.drop_index(batch_op.f('ix_clientes_alegra_id'))

    op.drop_table('clientes')
    with op.batch_alter_table('centros_costo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_centros_costo_codigo'))

    op.drop_table('centros_costo')
    # ### end Alembic commands ###
